# Generated by Django 3.2 on 2022-04-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.PositiveIntegerField()),
                ('book_name', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, choices=[('Education', 'Education'), ('History', 'History'), ('Maths', 'Maths'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Novels', 'Novels'), ('Commics', 'Commics'), ('Sci-fi', 'Sci-fi'), ('Fashion', 'Fashion'), ('Entertainment', 'Entertainment'), ('Romantic', 'Romantic'), ('Fantacy', 'Fantacy')], max_length=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
